### ISSUE TITLE
Giganode node doesn't exist anymore

### ISSUE THREAD

**Issue by aklowther** [kukai-wallet/kukai-core-swift#1]
`Models/Config/TezosNodeClientConfig defaultMainnetURLs.primaryNodeURL` is no longer in service as of October 1, 2021.   This should migrate to another node, ex: `https://mainnet.smartpy.io`

https://twitter.com/GigaNode/status/1435265400699342854?s=20

**Comment by aklowther** [comment]
That may be the goal but in practice, the node is down.  I guess it doesn't matter that much if you have a fallback URL.  I've only used this SDK for 2 minutes (literally), so I haven't gotten that far into understanding it.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1672012/137580197-c433d163-7bcc-4170-baed-0af317af5611.png">

**Comment by simonmcl** [comment]
@aklowther ping might be disabled on the server, or it could have been down briefly due to an issue.

I was working on the develop branch of this yesterday. I tested mainnet balance requests and it was fine against giganode. I'll keep an eye on it and change the default if it does go down. But it's not necessary right now to change it.

If it does go down, the config object allows you to pass in your own urls. That convenience init is just to help people new to tezos or new to the swift library to get up and running to conduct tests. Most apps end up deploying their own nodes and will point to their own anyway



Also if you do end up using this library for your own app, let us know. It's mainly for our own use cases, but it can help us secure funding if we can show others are relying on it
