### ISSUE TITLE
Why not support cocoapods integration

### ISSUE THREAD

**Issue by developerjet** [kukai-wallet/kukai-core-swift#6]
Why don't you support the cocoapods integration method? It's because my integration through packge is very slow and will conflict with the files of other libraries.

**Comment by simonmcl** [comment]
@developerjet I had numerous issues with cocoapods when I bought an M1 powered mac, it caused many issues and took a very long time to resolve. Several dependencies of cocoapods are not actively maintained and take months to update. Also one of my iOS dependencies for this library didn't support cocoapods and another was crashing on cocoapods only. I haven't checked if they are working, as I don't use cocoapods anymore anyway

SPM has matured greatly, is natively integrated with Xcode and is easier to maintain as you don't have to additionally deploy new updates via cocoapods trunk. There shouldn't be much of a difference between the download times on cocoapods trunk versus github. Its quite long at the minute as I have to use a dependency that itself has many many dependencies. I've tried to ask them to reduce their footprint and avoid using unnecessary libraries, but they don't seem to interested in improving the download side

Due to all the issues i've had with it recently, I think its unlikely i'll add cocoapods support as it will be very time consuming to keep it maintained
